version: '3.8'
services:
  todo-nginx:
    container_name: "todo-nginx"
    build:
      context: ./docker/nginx
    depends_on:
      - todo-app
    ports:
      - 80:80
    volumes:
      - ./:/src

  todo-app:
    container_name: "todo-app"
    build:
      context: ./docker/php
    depends_on:
      - todo-mysql
    volumes:
      - ./:/src
      - /src/node_modules
      - /src/vendor
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  todo-mysql:
    image: mysql:8.0.37
    command: --max_allowed_packet=32505856
    container_name: "todo-mysql"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=todolistapi
    ports:
      - 3306:3306
